name: build image

concurrency:
  group: ${{ github.ref }}-image
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v2
      if: github.ref_type == 'branch'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: ghcr.io/${{ github.repository }}
        flavor: |
          latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=semver,pattern={{version}}
    - uses: docker/build-push-action@v3
      with:
        push: true
        pull: true
        no-cache: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
